//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ItemId { get; set; }
        public int ItemNumber { get; set; }
        public string ItemDescription { get; set; }
        public double ItemPrice { get; set; }
        public int ItemQuantity { get; set; }
        public double ItemValue { get; set; }
        public double ItemCost { get; set; }
        public System.DateTime ItemCreatedDate { get; set; }
    }
}
